-- Jarvis conversation registry (per user). Jarvis chat_ids are generated by the
-- client and used as chat_messages.chat_id; this table lets us list a user's
-- Jarvis conversations (the History menu) from the DB instead of localStorage.

create table if not exists public.jarvis_chats (
    id uuid primary key,
    user_id uuid not null references auth.users (id) on delete cascade,
    title text not null default 'New chat',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists jarvis_chats_user_created_idx
    on public.jarvis_chats (user_id, created_at desc);

alter table public.jarvis_chats enable row level security;

drop policy if exists "jarvis_chats_select_own" on public.jarvis_chats;
create policy "jarvis_chats_select_own" on public.jarvis_chats
    for select using (auth.uid() = user_id);

drop policy if exists "jarvis_chats_insert_own" on public.jarvis_chats;
create policy "jarvis_chats_insert_own" on public.jarvis_chats
    for insert with check (auth.uid() = user_id);

drop policy if exists "jarvis_chats_update_own" on public.jarvis_chats;
create policy "jarvis_chats_update_own" on public.jarvis_chats
    for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "jarvis_chats_delete_own" on public.jarvis_chats;
create policy "jarvis_chats_delete_own" on public.jarvis_chats
    for delete using (auth.uid() = user_id);

grant select, insert, update, delete on public.jarvis_chats to authenticated;
